apiVersion: v1
kind: Pod
metadata:
  name: flink-job-submit-bus
  namespace: batch
spec:
  restartPolicy: Never
  containers:
  - name: flink-client
    image: manhlm29/flink-bus-job:1.0
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_BROKER
        value: "kafka-broker-1:29092"
      - name: WAREHOUSE_HOST
        value: "datawarehouse"
      - name: WAREHOUSE_PORT
        value: "5432"
      - name: WAREHOUSE_DB
        value: "warehousedb"
      - name: WAREHOUSE_USER
        value: "admin"
      - name: WAREHOUSE_PASSWORD
        value: "admin123"
    command:
      - sh
      - -c
      - |
        echo "Waiting for JobManager..."
        sleep 10  # Chờ xíu cho JobManager khởi động xong hẳn
        
        echo "🚀 Submitting PyFlink Job..."
        
        # Lệnh submit đơn giản, không cần -j vì JAR đã có sẵn trong lib rồi
        /opt/flink/bin/flink run \
          -m flink-jobmanager:8081 \
          -p 2 \
          -py /app/bus_positions_job.py
    
    # Vẫn cần mount config để client biết cấu hình cluster (cổng 6124, etc.)
    volumeMounts:
      - name: flink-config
        mountPath: /opt/flink/conf/flink-conf.yaml
        subPath: flink-conf.yaml
  
  volumes:
    - name: flink-config
      configMap:
        name: flink-config