apiVersion: batch/v1
kind: Job
metadata:
  name: init-kafka
  namespace: batch
spec:
  template:
    spec:
      containers:
      - name: init-kafka
        image: confluentinc/cp-kafka:7.6.0
        command:
        - /bin/sh
        - -c
        - |
          kafka-topics --bootstrap-server kafka-broker-1:29092 --list && \
          kafka-topics --bootstrap-server kafka-broker-1:29092 --create --if-not-exists --topic bus.public.data --replication-factor 1 --partitions 1 && \
          kafka-topics --bootstrap-server kafka-broker-1:29092 --list
      restartPolicy: OnFailure