apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: batch
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: internal
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: batch
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: internal
    targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: batch
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.6.0
        ports:
        - containerPort: 9092
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-0.zookeeper-headless.batch.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.batch.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.batch.svc.cluster.local:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        # Cấu hình dynamic hostname cho từng Pod trong StatefulSet
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(POD_NAME).kafka-headless.batch.svc.cluster.local:9092"
        # Tự động sinh Broker ID dựa trên tên Pod (kafka-0 -> 0, kafka-1 -> 1)
        - name: KAFKA_BROKER_ID_GENERATION_ENABLE
          value: "true"
        # CẤU HÌNH CHỊU LỖI (FAULT TOLERANCE)
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        # Tăng thời gian chờ để tránh crash khi khởi động nặng
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10