apiVersion: v1
kind: PersistentVolume
metadata:
  name: datalake-pv
  labels:
    type: local
spec:
  storageClassName: manual-datalake
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/volume_sgp1_01/datalake-data"
  # use node 1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datalake-pvc
  namespace: batch
spec:
  storageClassName: manual-datalake
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalake
  namespace: batch
  labels:
    app: datalake
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: datalake
  template:
    metadata:
      labels:
        app: datalake
    spec:
      # use node 1
      nodeSelector:
        node-role.kubernetes.io/manager: "true"
      
      # Security Context (User 1000)
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true

      containers:
        - name: postgresql
          image: debezium/postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "datalakedb"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin123"
          
          # Giới hạn tài nguyên
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: datalake-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: datalake
  namespace: batch
spec:
  type: NodePort
  selector:
    app: datalake
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30054
