# Use the official Flink image as the base image
FROM flink:1.20.2-scala_2.12
# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Install the Apache Flink Python API
RUN pip3 install apache-flink==1.20.2
RUN mkdir -p /opt/flink/jars
# Copy necessary Flink connector JAR files
COPY flink-connector-jdbc-3.3.0-1.20.jar /opt/flink/jars/
COPY flink-connector-kafka-3.3.0-1.20.jar /opt/flink/jars/
COPY flink-sql-connector-kafka-3.3.0-1.20.jar /opt/flink/jars/
COPY flink-sql-json-1.20.0.jar /opt/flink/jars/
COPY postgresql-42.7.3.jar /opt/flink/jars/
WORKDIR /app
# Copy the Flink job script
COPY bus_positions_job.py /app/bus_positions_job.py
# Run the Flink job using Python
CMD ["python3", "/app/bus_positions_job.py"]